services:
    auth:
        container_name: auth
        build:
            context: ./backend/auth
            dockerfile: Dockerfile
        image: auth
        ports:
            - '8081:8081'
        networks:
            - app-network
        volumes:
            - ./certs:/app/certs
            - ./uploads:/app/uploads
            - ./db:/app/db
            - /app/node_modules
        env_file: './.env'
        environment:
            - DB_PATH=/app/db/auth.db
            - PORT=8081
            - HOST=0.0.0.0
            - DATABASE_URL=file:/app/db/auth.db
    chat:
        container_name: chat
        build:
            context: ./backend/chat
            dockerfile: Dockerfile
        image: chat
        ports:
            - '8082:8082'
        networks:
            - app-network
        volumes:
            - ./certs:/app/certs
            - ./uploads:/app/uploads
            - ./db:/app/db
            - /app/node_modules
        env_file: './.env'
        environment:
            - DB_PATH=/app/db/chat.db
            - PORT=8082
            - HOST=0.0.0.0
            - DATABASE_URL=file:/app/db/chat.db

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - ./certs:/app/certs
        networks:
            - app-network
        env_file: './.env'

    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./infra/nginx
            dockerfile: nginx.Dockerfile
        networks:
            - app-network
        ports:
            - '81:80'
            - '443:443'
        environment:
            - NGINX_HOST=0.0.0.0
            - NGINX_PORT=80
        volumes:
            - ./infra/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/ssl
        depends_on:
            - auth
            - frontend

networks:
    app-network:
        driver: bridge
