services:
    auth:
        build:
            context: ./backend/auth
            dockerfile: Dockerfile
        image: auth
        ports:
            - '8081:8081'
        networks:
            - app-network
        volumes:
            - ./certs:/app/certs
            - ./uploads:/app/uploads
            - ./db:/app/db
        env_file: './.env'
        environment:
            - DATABASE_URL=file:/app/db/auth.db

    match:
        build:
            context: ./backend/match
            dockerfile: Dockerfile
        image: match
        ports:
            - '8082:8082'
        networks:
            - app-network
        volumes:
            - ./db:/app/db
            - ./uploads:/app/uploads
            - ./certs:/app/certs
            - ./backend/match/src:/app/src
        env_file: './.env'
        environment:
            - DATABASE_URL=file:/app/db/match.db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - ./certs:/app/certs
        networks:
            - app-network
        env_file: './.env'

networks:
    app-network:
        driver: bridge
