services:
    auth:
        build:
            context: ./backend/auth
            dockerfile: Dockerfile
        image: auth
        ports:
            - '8081:8081'
        networks:
            - app-network
        volumes:
            - ./certs:/app/certs
            - ./uploads:/app/uploads
            - ./db:/app/db
        env_file: './.env'
        environment:
            - DATABASE_URL=file:/app/db/auth.db

    match:
        build:
            context: ./backend/match
            dockerfile: Dockerfile
        image: match
        ports:
            - '8082:8082'
        networks:
            - app-network
        volumes:
            - ./db:/app/db
            - ./uploads:/app/uploads
            - ./certs:/app/certs
            - ./backend/match/src:/app/src
        env_file: './.env'
        environment:
            - DATABASE_URL=file:/app/db/match.db
        depends_on:
            - auth

    chat:
        build:
            context: ./backend/chat
            dockerfile: Dockerfile
        image: chat
        ports:
            - '8083:8083'
        networks:
            - app-network
        volumes:
            - ./db:/app/db
            - ./uploads:/app/uploads
            - ./certs:/app/certs
            - ./backend/chat/src:/app/src
        env_file: './.env'
        environment:
            - DATABASE_URL=file:/app/db/chat.db
        depends_on:
            - auth

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - ./certs:/app/certs
        networks:
            - app-network
        env_file: './.env'
        depends_on:
            - auth
            - match
            - chat
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./infra/nginx
            dockerfile: nginx.Dockerfile
        networks:
            - app-network
        ports:
            - '81:80'
            - '443:443'
        environment:
            - NGINX_HOST=0.0.0.0
            - NGINX_PORT=80
            - FRONTEND=https://localhost
        volumes:
            - ./infra/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/ssl
        depends_on:
            - auth
            - match
            - chat
            - frontend

networks:
    app-network:
        driver: bridge
